name: Node.js CI and Deployment

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Change this to the Node.js version you're using

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm test

    - name: Deploy to Server
      run: |
        # Configure SSH using the private key stored as a secret
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Add the server's SSH fingerprint to known_hosts
        ssh-keyscan -H target_server_ip_or_domain >> ~/.ssh/known_hosts
      
        # Deploy your code to the server using SSH commands
        # Example: scp, rsync, or any other deployment commands
        # Replace the following line with your actual deployment command
        ssh -i ~/.ssh/id_rsa ec2-user@target_server_ip_or_domain "echo 'Deployment Successful!'"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
